{
	"_type":      "Pixelbox color theme",
	"name":       "lacia",
	"version":    1,
	"background": "#656092",
	"border":     "#dcd2d2",
	"button":     "#929292",
	"handle":     "#8563d8",
	"handletxt":  "#000000",
	"b_low":      "#73707d",
	"b_med":      "#1e1c21",
	"b_high":     "#b5b4bb",
	"f_low":      "#797979",
	"f_med":      "#ffffff",
	"f_high":     "#f5f4f4",
	"select":     "#4b35ff",
	"checker":    "#40303f"
}